### ISSUE TITLE
Server only version?

### ISSUE THREAD

**Issue by chmac** [p-j/meteor-crypto-md5#1]
Firstly, thanks for this package, it's a real time saver.

I'm nervous about shipping large volumes of code to the client. We need to use md5 on the server but not on the client. To that end I created a [crypto-md5-server](https://atmospherejs.com/superlumen/crypto-md5-server) package which simply requires your package on the server only. But I wonder if there's a better way?

I guess with the current status of the packaging system, there might not be, but figured I'd ping you the question anyway...

**Comment by p-j** [comment]
Hi @chmac  and thanks for your interest in this package !

I understand fully your point on the size of JS being shipped to the client, this can really be a bottleneck ! 

I think for what you want to do the Node.js core module [`crypto`](https://nodejs.org/api/crypto.html) is enough. This way it ships only on the server and you can use [`crypto.createHash(algorithm)`](https://nodejs.org/api/crypto.html#crypto_crypto_createhash_algorithm) and [`hash.update(data[, input_encoding])`](https://nodejs.org/api/crypto.html#crypto_hash_update_data_input_encoding) to hash the data in MD5 or other popular hash algorithm such as sha1, sha256, sha512. The list of available algorithm will vary with the version of OpenSSL you have.

Then use [`hash.digest([encoding])`](https://nodejs.org/api/crypto.html#crypto_hash_digest_encoding) to get the generated hash in the expected encoding.

I hope this helps.

**Comment by chmac** [comment]
I had thought about using node's native crypto library. Probably a more elegant solution for server side only hashing I guess. I do like the simplicity of this API though, simply calling a function and getting the md5 back is neater. My immediate challenge with node's crypto was being able to use it in the app itself, but I could create a package to just export it, as we do for [assert](https://github.com/superlumen/meteor-assert). I'm even thinking of creating a simple interface to require any core node packages on demand, but I digress... :-)

Thanks for the follow up. Guess there's no better way to expose this API server side only at the moment, so I'll close this issue.
